### ISSUE TITLE
Broken link in the Readme section

### ISSUE THREAD

**Issue by rubensfig** [opencord/cord#4]
Hello,

The link in the README.md file to CORD-in-a-box is broken.
https://github.com/opencord/cord/blob/master/docs/quickstart.md

**Comment by llpeterson** [comment]
The Markdown files (in /docs directories) are being modified to reflect the
new release. And, they are being compiled into a GitBook-based guide. See
http://guide.opencord.org (still a work in progress).

Larry

**Comment by rubensfig** [comment]
Ok, thank you.
